sudo: false
language: node_js
node_js:
  - "10"
before_install:
  - 'if [ -n "$TSD_GITHUB_TOKEN" ]; then echo {\"token\": \"$TSD_GITHUB_TOKEN\"} > .tsdrc; fi'
cache:
  directories:
    - node_modules
